version: '3.7'

services: 
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    # container_name: elasticsearch
    environment:
      - discovery.type=single-node
    volumes:
      - ./elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
